version: "3.4"

services:
  mysql:
    image: mysql:5.7
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build: nginx
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 443:443
    volumes:
      # Project files
      - app-magento2-sync:/var/www/html:nocopy
      # Custom configuration
      - ${PROJECT_LOCATION}/docker/local/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      # Project files
      - app-magento2-sync:/var/www/html:nocopy
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/home/www-data/.ssh:ro
    tty: true

volumes:
  app-magento2-sync:
    external: true
  mysql: {}
